import "./globals.css";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Next Blog",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} flex flex-col min-h-screen max-w-[800px] px-4 mx-auto w-full`}
      >
        <header className="py-6  text-white rounded-lg p-4  mt-4 text-center ">
          <div>
            <h1 className="font-bold text-lg">{`Rakesh's Blog`}</h1>
            <p>👋 Hey welcome to my tech blog. 💻</p>
          </div>
        </header>
        <main className="flex-1 py-4">{children}</main>
        <footer className="text-center p-4 border-t  border-t-slate-500">
          <p>Devloped by Rakesh.</p>
        </footer>
      </body>
    </html>
  );
}
